### ISSUE TITLE
what seasons/years to include?

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#112]
I just finished putting together this spreadsheet to get a better sense of which cameras were operational when: https://docs.google.com/spreadsheets/d/12F1dqicDzqo5jgYea0d8uKjulvZsR9SBHq51wLpVLQk/edit#gid=0
(I think it's related to the one you might be working on, but specifically focused on the late dry season. Please let me know if you want any help putting together the one you mentioned in your email)

I'm starting to think about what restrictions should be imposed on counting a camera for a particular season (i.e. does it need to have been operational for half the season? 5 days? one month?) and coming back to thinking about including cameras that were not operational for all four years. No cameras have data for the full late dry season for all four years (most cameras were taken down in October 2019). 20 cameras are missing at least one year's worth of data. I might have seen something while reading the camtrap package info about including cameras that don't have data for all the seasons, I'll go back and see if I can find it. I just wanted to get this written out while I'm thinking about it.

**Comment by kaitlyngaynor** [comment]
Great investigation!

For more info, I'm essentially just planning to re-create the camera
operation spreadsheet so that there is only one row per camera. I have done
this manually a couple of times and *always* make mistakes so I'm trying to
figure out a way to code it up so it doesn't require copy-pasting and brain
energy. But I'm waiting to see if Meredith has successfully worked with it,
so as to avoid re-inventing the wheel. Stay tuned.

I think I set some threshold of 10 days (for considering a camera
operational) at some point, which seems low. I think a lot of best
practices for occupancy surveys suggest 2 weeks so maybe this is
justifiable. See this paper
https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210X.13370
"Running
a camera at a site for 2 weeks was most efficient for detecting new
species, but 3–4 weeks were needed for precise estimates of local detection
rate, with no gains in precision observed after 1 month."

And to clarify, the cameras weren't taken down, that's just when they were
last checked—they should still have data, it's just on SD cards sitting on
Mozambique, which will be returning to the US in March, so we may still be
able to fill in those gaps.

**Comment by klg-2016** [comment]
Sounds good for the spreadsheet! Happy to help with the manual edits if
they're necessary

Thanks for sending the paper over, I'll check it out! I think for my thesis
I had one camera operational for 23 days, which luckily fits with that
suggestion.

And that absolutely makes sense for the cameras, I just wasn't thinking.
That's exciting that new data is coming back next month!

**Comment by klg-2016** [comment]
more relevant conversation on this in Issue #114 , so closing for now
