### ISSUE TITLE
filtering correctly?

### ISSUE THREAD

**Issue by klg-2016** [kaitlyngaynor/gorongosa-mesocarnivores#93]
https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/blob/1959066287fa0a1067a9d709b0dbfa90843cbe1c/scripts/species-interaction-model/01-prep-data-for-occupancy-analysis.R.R#L176

Another note to self, just to confirm that the dates are being filtered correctly

**Comment by kaitlyngaynor** [comment]
Did you ever confirm? 

(just trying to clear out issues for simplicity but let me know if I'm overstepping)

**Comment by klg-2016** [comment]
I don't think I did, because we pivoted away from the multi-site work before I took the time to do so. So we can close this for now, and come back to it when/if we return to the multi-site work.

Not overstepping, thank you for helping me clear! It's a good reminder to stay on top of my issues, sorry you're ending up closing so many of them.

**Comment by kaitlyngaynor** [comment]
No worries! Also, if it's helpful for organizing issues, you could potentially explore projects (to split up the multi-season, multi-site, etc issues): https://github.com/kaitlyngaynor/gorongosa-mesocarnivores/projects

I've never used this, though, and since we are really just focusing on the multi-season for now, it may not be worth it. Just flagging
